### ISSUE TITLE
Feature request: Scoreboard applied to multiple worlds

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/ScoreBoards#4]
Spigot 1.12.2
ScoreBoards 1.2

The configuration allows one to set a different scoreboard for any listed world. It would be nice to apply the same scoreboard to sets of worlds (for example, world, world_nether, and world_the_end), but different scoreboards to other sets of worlds. The objective is to avoid having multiple worlds with copies of the same scoreboard values. Of course, this would still allow specification of different scoreboards for every world.

I can imagine two ways to configure this (and there are no doubt more):

1. Change the node to a unique identifier, then list the worlds to which it applies. Configuration example:
```
boards:
  '1':
    worlds:
    - world
    - world_nether
    - world_the_end
    title: '&r▭▭▭▭ %servername% ▭▭▭▭'
    lines:
    - '&7world:'
    - '    &r%multiverse_world_alias%'
    - '&7loc:'
    - '    &r%player_x% %player_y% %player_z%'
  '2':
    worlds:
      - world_lobby
...
```
2. Allow a keyword to copy a previously defined scoreboard to the current world. Configuration example:
```
worlds:
  world:
    title: '&r▭▭▭▭ %servername% ▭▭▭▭'
    lines:
    - '&7world:'
    - '    &r%multiverse_world_alias%'
    - '&7loc:'
    - '    &r%player_x% %player_y% %player_z%'
  world_nether:
    copy: world
  world_the_end
    copy: world
...
```
I prefer (1), but anything that accomplishes the objective would be great.
